### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by k1ll1n** [GiviMAD/rustpotter-java#4]
Version: `io.github.givimad:rustpotter-java:3.0.0-beta.4`
My code:

```kotlin
    val rustpotterBuilder = RustpotterBuilder()
    val rustpotter = rustpotterBuilder.build()
    rustpotterBuilder.delete()
```
Error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long io.github.givimad.rustpotter_java.RustpotterBuilder.init()'
	at io.github.givimad.rustpotter_java.RustpotterBuilder.init(Native Method)
	at io.github.givimad.rustpotter_java.RustpotterBuilder.<init>(RustpotterBuilder.java:10)
	at Test4Kt.main(test4.kt:16)
	at Test4Kt.main(test4.kt)
```

**Comment by GiviMAD** [comment]
You need to run ```Rustpotter.loadLibrary()``` at first so the native library gets loaded. 
I need to improve the documentation.

**Comment by k1ll1n** [comment]
Yes it helped thanks.

**Comment by k1ll1n** [comment]
Yes it helped thanks.
